#!/bin/sh

# Include config file.
. ~/.config/lemonbar/.config

# Determine the status of each workspace using a loop. Focused is green, unfocused is white, empty is grey.
desktops(){
    currentSeparator="${separator}"

    focusedDesktop=$(bspc query -D -d)
    lastDesktop=$(bspc query -D | tail -n1)

    for desktop in $(bspc query -D); do
        numberOfNodes=$(bspc query -N -d ${desktop} | wc -l)

        if [[ "${desktop}" == "${focusedDesktop}" ]]; then
            color=${green}
        elif [[ ${numberOfNodes} -gt 0 ]]; then
            color=${foreground}
        else
            color=${grey}
        fi

        if [[ "${desktop}" == "${lastDesktop}" ]]; then
            currentSeparator=""
        fi

        desktops+="%{F${color}}%{A:bspc desktop -f ${desktop}:}${desktop}%{A}${currentSeparator}"
    done

    echo "${desktops}"
}

# Pipe functions to the bar infinitely.
while true; do
	echo "%{c}$(desktops)"
done | lemonbar -g ${panelWidth}x${panelHeight}+${panelX}+${bottomPanelY} -f "${font}-${fontSize}" -f "${iconFont}" -B "${background}" -p -d | \
    while true; do read line; eval $line; done &
