#!/bin/bash

# Include config file.
. ~/.config/lemonbar/config

# Fetch current network connection state and SSID.
network(){
    networkState=$(grep -R "up" /sys/class/net/*/operstate)
    networkSSID=$(iwgetid -r)

    if [[ ${networkState} != "" && ${networkSSID} != "" ]]; then
        network=${networkSSID}
    elif [[ ${networkState} != "" ]]; then
    	network="Online"
    else
        network="Offline"
    fi

    if [[ ${networkState} == "" ]]; then
        networkColor=${red}
    else
        networkColor=${foreground}
    fi

    echo "%{F$networkColor} ${network}"
}

# Fetch current volume state and mute state.
volume(){
    volumeState=$(ponymix get-volume)

    # level-based icon
    if [[ ${volumeState} -eq 0 ]]; then
    	volumeIcon=""
    elif [[ ${volumeState} -le 50 ]]; then
    	volumeIcon=""
    else
    	volumeIcon=""
    fi

    if $(ponymix is-muted); then
    	volumeColor=${red}
    else
        volumeColor=${foreground}
    fi

    echo "%{F$volumeColor}${volumeIcon} ${volumeState}%"
}

# Fetch the current percentage of the battery's capacity.
battery(){
    batteryState=$(cat /sys/class/power_supply/BAT0/status)
    batteryPower=$(cat /sys/class/power_supply/BAT0/capacity)

    # Determine battery icon based on capacity.
    if [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 20 ]]; then
    	batteryIcon=""
    elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 40 ]]; then
    	batteryIcon=""
    elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 60 ]]; then
    	batteryIcon=""
    elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 80 ]]; then
        batteryIcon=""
    elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 100 ]]; then
        batteryIcon=""
    else
        batteryIcon=""
    fi

    if [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 20 ]]; then
        batteryColor=${red}
    else
        batteryColor=${foreground}
    fi

    echo "%{F$batteryColor}${batteryIcon} ${batteryPower}%"
}

# Fetch the current date.
calendar(){
    calendar=$(date "+%a, %b %d, %Y")
    echo "%{F$foreground} ${calendar}"
}

# Fetch the current time.
clock(){
    clock=$(date "+%I:%M:%S %p")
    echo "%{F$foreground} ${clock}"
}

# Pipe functions to the bar infinitely.
while true; do
	echo "%{c}$(network)${separator}$(volume)${separator}$(calendar)${separator}$(clock)"
done | lemonbar -g ${panelWidth}x${panelHeight}+${panelX}+${topPanelY} -f "${font}-${fontSize}" -f "${iconFont}" -B "${background}" -F "${foreground}" -p -d  | \
    while true; do read line; eval $line; done &
