#!/bin/bash

# Include config file.
. ~/.config/lemonbar/config

# Fetch current network connection state and SSID.
network(){
    networkState=$(grep -R "up" /sys/class/net/*/operstate)
    networkSSID=$(iwgetid -r)

    if [[ ${networkState} != "" && ${networkSSID} != "" ]]; then
        network=${networkSSID}
    elif [[ ${networkState} != "" ]]; then
    	network="Online"
    else
        network="Offline"
    fi

    if [[ ${networkState} == "" ]]; then
        networkColor=${red}
    else
        networkColor=${foreground}
    fi

    echo "%{F$networkColor} ${network}"
}

# Fetch current dropbox sync status.
dropbox(){
    dropboxInfo=$(dropbox-cli status)

    if [[ $dropboxInfo == "Connecting..." || $dropboxInfo == "Starting..." ]]; then
        dropbox="Connecting"
        dropboxColor=${green}
    elif [[ $(echo $dropboxInfo | grep "Syncing") != "" || $(echo $dropboxInfo | grep "Downloading") != "" || $(echo $dropboxInfo | grep "Indexing") != "" ]]; then
        dropbox="Syncing"
        dropboxColor=${green}
    elif [[ $dropboxInfo == "Dropbox isn't running!" ]]; then
        dropbox="Offline"
        dropboxColor=${red}
    else
        dropbox="Idle"
        dropboxColor=${foreground}
    fi

    echo "%{F$dropboxColor} ${dropbox}"
}

# Fetch current volume state and mute state.
volume(){
    volumeState=$(ponymix get-volume)

    # level-based icon
    if [[ ${volumeState} -eq 0 ]]; then
    	volumeIcon=""
    elif [[ ${volumeState} -le 50 ]]; then
    	volumeIcon=""
    else
    	volumeIcon=""
    fi

    if $(ponymix is-muted); then
    	volumeColor=${red}
    else
        volumeColor=${foreground}
    fi

    echo "%{F$volumeColor}${volumeIcon} ${volumeState}%"
}

# Fetch the current percentage of the battery's capacity.
battery(){

    # Only display battery information if a battery exists.
    if [[ -e /sys/class/power_supply/BAT0/capacity ]]; then
        batteryState=$(cat /sys/class/power_supply/BAT0/status)
        batteryPower=$(cat /sys/class/power_supply/BAT0/capacity)

        # Determine battery icon based on capacity and state.
        if [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 20 ]]; then
        	batteryIcon=""
            batteryColor=${red}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 40 ]]; then
        	batteryIcon=""
            batteryColor=${foreground}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 60 ]]; then
        	batteryIcon=""
            batteryColor=${foreground}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 80 ]]; then
            batteryIcon=""
            batteryColor=${foreground}
        elif [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 100 ]]; then
            batteryIcon=""
            batteryColor=${foreground}
        else
            batteryIcon=""
            batteryColor=${green}
        fi

        echo "%{F$batteryColor}${batteryIcon} ${batteryPower}%${separator}"
    fi
}

# Fetch the current date.
calendar(){
    calendar=$(date "+%a, %b %d, %Y")
    echo "%{F$foreground} ${calendar}"
}

# Fetch the current time.
clock(){
    clock=$(date "+%I:%M %p")
    echo "%{F$foreground} ${clock}"
}

# Pipe functions to the bar infinitely.
while true; do
	echo "%{c}$(network)${separator}$(dropbox)${separator}$(volume)${separator}$(battery)$(calendar)${separator}$(clock)"
done | lemonbar -g ${panelWidth}x${panelHeight}+${panelX}+${topPanelY} -f "${font}-${fontSize}" -f "${iconFont}" -B "${background}" -F "${foreground}" -p -d  | \
    while true; do read line; eval $line; done &
