#!/bin/bash

# Include config file.
. ~/.config/lemonbar/config

# Determine the status of each workspace using a loop. Focused is green, unfocused is white, empty is grey.
workspaces(){
    workspaces=""
    currentSeparator="${separator}"

    filledWorkspaces=$(i3-msg -t get_workspaces | grep -Po '"'"name"'"\s*:\s*"\K([^"]*)')
    focusedWorkspace=$(i3-msg -t get_outputs | sed 's/.*"current_workspace":"\([^"]*\)".*/\1/')
    numberOfWorkspaces=$((${#workspaceNames[@]} - 1))

    for ((i=1; i<=${numberOfWorkspaces}; i++)); do
        if [[ ${focusedWorkspace} -eq ${i} ]]; then
            color=${green}
        elif [[ $(echo ${filledWorkspaces} | grep -w "${i}") != "" ]]; then
            color=${foreground}
        else
            color=${grey}
        fi

        if [[ ${i} -eq ${numberOfWorkspaces} ]]; then
            currentSeparator=""
        fi

        workspaces+="%{F${color}}%{A:i3-msg workspace ${i}:}${workspaceNames[i]}%{A}${currentSeparator}"
    done

    echo "${workspaces}"
}

# Pipe functions to the bar infinitely.
while true; do
	echo "%{c}$(workspaces)"
done | lemonbar -g ${panelWidth}x${panelHeight}+${panelX}+${bottomPanelY} -f "${font}-${fontSize}" -f "${iconFont}" -B "${background}" -p -d | \
    while true; do read line; eval $line; done &
