#!/bin/sh

# Array of packages to install.
packages=(
    # System tools
    "termite"
)

buildroot="$(mktemp -d)"

# Ask for user password only once.
sudo -v

# Fetch Dave Reisner's key to be able to verify cower.
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 487EACC08557AD082088DABA1EB2638FF56C0C53

# Make sure AUR dependencies are installed.
sudo pacman -S --needed --noconfirm base-devel git

# Build AUR helper.
mkdir -p "$buildroot"
cd "$buildroot" || exit 1

git clone "https://aur.archlinux.org/cower.git"
git clone "https://aur.archlinux.org/pacaur.git"

cd "${buildroot}/cower" || exit 1
makepkg --syncdeps --install --noconfirm

cd "${buildroot}/pacaur" || exit 1
makepkg --syncdeps --install --noconfirm

cd "$HOME" || exit 1
rm -rf "$buildroot"
