#!/bin/sh

# Array of packages to install.
packages=(
    # Basic packages
    "termite"                           # Terminal emulator.
    "neofetch"                          # Display information about system.
    "txtw-git"                          # Returns text width in pixels.
    "infinality-bundle"                 # Patches to improve font rendering.
    "jq"                                # Tool for parsing jquery.
    "wget"                              # Tool for downloading files from the internet.
    "unzip"                             # Tool for extracting zip archives.
    "xclip"                             # Allows manipulation of clipboard from terminal.

    # Editing tools
    "atom-editor"                       # Hackable text editor.
    "gvfs"                              # Used by atom to delete files.
    "intellij-idea-community-edition"   # Java IDE.

    # Shell tools
    "zsh"                               # Bash shell replacement.
    "zsh-syntax-highlighting"           # Syntax highlighting plugin for zsh.

    # Internet
    "chromium"                          # Web browser.
    "qutebrowser"                       # Small web browser for encapsuling web apps.
    "dropbox"                           # Cloud storage.
    "dropbox-cli"                       # Terminal interface for dropbox.

    # Window management
    "bspwm"                             # Window manager.
    "sxhkd"                             # Hotkey daemon.
    "lemonbar-xft-git"                  # Panel displayer.
    "conky"                             # Panel gap helper.
    "compton"                           # Compositer.
    "rofi"                              # Program run menu.

    # Image realted
    "feh"                               # Image viewer / wallpaper setter.
    "scrot"                             # Screenshot tool.
    "imagemagick"                       # Terminal image manipulation.

    # Music related
    "spotify"                           # Music streaming service.
    "playerctl"                         # Music control tool.
    "cava-git"                          # Terminal music visualizer.
    "ponymix"                           # Volume control tool.
)

# Array of stows to be installed -- which originate from the home folder, some stows require special instructions.
homeStows=(
    "bin"
    "cava"
    "neofetch"
    "pacaur"
    "qutebrowser"
    "ranger"
    "termite"
    "wallpaper"
    "wm"
    "x"
)

# Ask for user password only once.
sudo -v

# Make sure script dependencies are installed.
echo "Checking dependencies."
sudo pacman -S --needed --noconfirm base-devel git stow

# Install stowed files from array.
echo "Installing dotfiles."

for ((i=0; i<=$((${#homeStows[@]} - 1)); i++)); do
    stow -d ~/dotfiles -t ~ ${homeStows[i]}
    echo "Dotfiles for ${homeStows[i]} installed."
done

    # Install stowed files which have special conditions.
    # Pacman
    sudo rm /etc/pacman.conf
    sudo stow -d ~/dotfiles -t / pacman--root
    echo "Dotfiles for pacman installed."

# Increase the size of the /tmp directory to be able build the large array of packages.
sudo mount -o remount,size=4G,noatime /tmp

# Fetch keys needed to verify cower and infinality.
echo "Fetching package keys."

    # Cower key.
    gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 487EACC08557AD082088DABA1EB2638FF56C0C53

    # Infinality key.
    sudo pacman-key -r 962DDE58
    sudo pacman-key -f 962DDE58
    sudo pacman-key --lsign-key 962DDE58

    # Refresh all keys.
    sudo pacman-key --refresh-keys

    # Synchronize repositories.
    pacaur -Sy

# Build AUR helper.
echo "Building AUR helper."

buildroot="$(mktemp -d)"

mkdir -p "$buildroot"
cd "$buildroot" || exit 1

git clone "https://aur.archlinux.org/cower.git"
git clone "https://aur.archlinux.org/pacaur.git"

cd "${buildroot}/cower" || exit 1
makepkg --syncdeps --install --noconfirm

cd "${buildroot}/pacaur" || exit 1
makepkg --syncdeps --install --noconfirm

cd "$HOME" || exit 1
rm -rf "$buildroot"

# Install packages from array.
echo "Installing user specified packages."

for ((i=0; i<=$((${#packages[@]} - 1)); i++)); do
    pacaur --noedit -S ${packages[i]}
done

# Change user shell.
echo "Changing user shell."
sudo chsh -s /bin/zsh $(whoami)

# Remove any orphanated packages.
echo "Removing orphanated packages."
sudo pacman -Rns $(pacman -Qtdq)
