#!/bin/sh

# Array of packages to install.
packages=(
    # Basic tools
    "termite"                   # Terminal emulator
    "vim"                       # Basic terminal text editor
    "atom-editor"               # Complex text editor
    "stow"                      # Dotfile management helper.

    # Internet
    "chromium"                  # Web browser

    # Window management
    "i3-gaps-git"               # Window manager
    "lemonbar-xft-git"          # Panel displayer
    "conky"                     # Panel helper

    # Image realted
    "feh"                       # Image viewer / wallpaper setter
    "scrot"                     # Screenshot tool
    "imagemagick"               # Terminal image manipulation

    # Music related
    "spotify"                   # Music streaming service
    "playerctl"                 # Music control tool
    "cava-git"                  # Terminal music visualizer
)

# Ask for user password only once.
sudo -v

# Increase the size of the /tmp directory to be able build the large array of packages.
sudo mount -o remount,size=4G,noatime /tmp

# Fetch Dave Reisner's key to be able to verify cower.
echo "Fetching package keys."
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 487EACC08557AD082088DABA1EB2638FF56C0C53

# Make sure AUR dependencies are installed.
echo "Checking AUR helper dependencies."
sudo pacman -S --needed --noconfirm base-devel git

# Build AUR helper.
echo "Building AUR helper."

buildroot="$(mktemp -d)"

mkdir -p "$buildroot"
cd "$buildroot" || exit 1

git clone "https://aur.archlinux.org/cower.git"
git clone "https://aur.archlinux.org/pacaur.git"

cd "${buildroot}/cower" || exit 1
makepkg --syncdeps --install --noconfirm

cd "${buildroot}/pacaur" || exit 1
makepkg --syncdeps --install --noconfirm

cd "$HOME" || exit 1
rm -rf "$buildroot"

# Install packages from array.
echo "Installing user specified packages."

for ((i=0; i<=${#packages[@]}; i++)); do
    pacaur -S ${packages[i]}
done

# Remove any orphanated packages.
echo "Removing orphanated packages."
sudo pacman -Rns $(pacman -Qtdq)
