#!/bin/bash

# Only run popup checker if a battery exists.
if [[ -d /sys/class/power_supply/BAT0 ]]; then
    while true; do
        # Fetch information on battery.
        batteryState=$(cat /sys/class/power_supply/BAT0/status)
        batteryPower=$(cat /sys/class/power_supply/BAT0/capacity)

        # Determine battery icon based on capacity and state.
        if [[ "${batteryState}" == "Discharging" && ${batteryPower} -le 20 ]]; then
            ~/.config/lemonbar/popup-spawner -c red -s "Battery power is low! Currently, it is at ${batteryPower} percent!"
            sleep 300
        fi
    done
else
    exit 0
fi
