#!/bin/bash

# Outside sources
i3config="$HOME/.config/i3/config"

# Fetch information from the X resource database.
background=$(xrdb -query | grep -i background | tail -c 8)
foreground=$(xrdb -query | grep -i foreground | tail -c 8)
black=$(xrdb -query | grep -i color0 | tail -c 8)
grey=$(xrdb -query | grep -i color8 | tail -c 8)
red=$(xrdb -query | grep -i color9 | tail -c 8)
green=$(xrdb -query | grep -i color10 | tail -c 8)
yellow=$(xrdb -query | grep -i color11 | tail -c 8)
blue=$(xrdb -query | grep -i color12 | tail -c 8)
magenta=$(xrdb -query | grep -i color13 | tail -c 8)
cyan=$(xrdb -query | grep -i color14 | tail -c 8)
white=$(xrdb -query | grep -i color15 | tail -c 8)

# Fetch information from i3 config
gapSize=$(awk '/gaps inner/ {print $3}' ${i3config})

# Select the names for the workspaces that are displayed on the workspace bar.
## These names are ondependant from i3 config -- workspaces in i3 config should be named 1-10.
workspaceNames=(
    ""               # 0 (No such workspace)
    "Web Browser"    # 1
    "Terminal"       # 2
    "Text Editor"    # 3
    "Unspecified"    # 4
    "Unspecified"    # 5
    "Unspecified"    # 6
    "Unspecified"    # 7
    "Unspecified"    # 8
    "Unspecified"    # 9
    "Music Player"   # 10
)

# Select which blocks are displayed on the status bar.
selectedBlocks=(
    "network"
    "dropbox"
    "volume"
#   "battery"
    "calendar"
    "clock"
)

# Fonts
fontSize=10
font="InputSans"
iconFont="FontAwesome"

# Bar panel settings
separator="%{F$foreground}   |│|   "

screenWidth=$(xrandr | awk '/Screen 0/ {print $8}')
screenHeight=$(xrandr | awk '/Screen 0/ {print $10}' | tr -d ",")

panelHeight=$((${gapSize} * 2))
panelWidth=$((${screenWidth} - ${panelHeight}))
panelX=${gapSize}
topPanelY=${gapSize}
bottomPanelY=$((${screenHeight} - ${panelHeight} - ${gapSize}))
