#!/bin/bash

# Import the universal config.
. ~/.universal

# Figure out how to make padding calculated. It should be whatever screen height is left after subtracting rofi's size.
rofi -show run \
-opacity 90 \
-hide-scrollbar \
-separator-style none \
-bw 0 \
-lines 3 \
-eh 2 \
-font "${monoFont} 12" \
-width ${screenWidth} \
-padding 480 \
-color-enabled \
-color-window "${background}, ${foreground}, ${foreground}" \
-color-normal "${background}, ${foreground}, ${background}, ${background}, ${accent}"
