#!/bin/sh

# Include config file.
. ~/.config/lemonbar/.config

# Create switchable desktops.
bspc monitor -d One Two Three Four Five

# Per desktop sizing.
for desktop in $(bspc query -D); do
    bspc config -d $desktop border_width ${borderSize}
    bspc config -d $desktop window_gap ${gapSize}
done

# Universal sizing.
bspc config top_padding $((${gapSize} * 3))
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding $((${gapSize} * 3))
bspc config split_ratio 0.50

# Colors.
bspc config focused_border_color "${foreground}"
bspc config normal_border_color "${background}"
bspc config presel_feedback_color "${magenta}"

# Misc settings.
bspc config auto_cancel true

# Set random wallpaper.
#localWallpapers=(~/.wallpaper/*)
#if [[ ! -e /tmp/bgnormal.jpg ]]; then
#    feh --bg-fill $(printf "%s\n" "${localWallpapers[RANDOM % ${#localWallpapers[@]}]}")
#fi

# Set wallpaper.
feh --bg-tile ~/.wallpaper/tiled/tweed.png

# Start programs.
compton --config ~/.config/compton/compton.conf -f &
dropbox &

# Start popup monitors.
~/.config/lemonbar/popups/updates &

# Start lemonbar panels.
~/.config/lemonbar/bars/status &
~/.config/lemonbar/bars/desktops &
