#!/bin/sh

# Include config file.
. ~/.universal
. ~/.config/lemonbar/.config

# Create switchable desktops.
bspc monitor -d One Two Three Four Five

# Per desktop sizing.
for desktop in $(bspc query -D); do
    bspc config -d $desktop border_width ${borderSize}
    bspc config -d $desktop window_gap ${gapSize}
done

# Universal sizing.
bspc config top_padding $((${gapSize} * 3))
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding $((${gapSize} * 3))
bspc config split_ratio 0.50

# Colors.
bspc config active_border_color "${foreground}"
bspc config focused_border_color "${foreground}"
bspc config normal_border_color "${background}"

# Misc configurations.
#bspc config borderless_monocle true
#bspc config gapless_monocle true
#bspc config focus_by_distance true
#bspc config history_aware_focus true

# Set random wallpaper.
#localWallpapers=(~/.wallpaper/*)
#if [[ ! -e /tmp/bgnormal.jpg ]]; then
#    feh --bg-fill $(printf "%s\n" "${localWallpapers[RANDOM % ${#localWallpapers[@]}]}")
#fi

# Set wallpaper.
feh --bg-fill ~/.wallpaper/oceanic_next.png

# Start programs.
compton --config ~/.config/compton/compton.conf -f &
dropbox &

# Start hacky scripts
~/bin/wallpaper-monitor &
~/.config/lemonbar/popups/updates &

# Start lemonbar panels.
~/.config/lemonbar/bars/status &

~/.config/lemonbar/bars/desktops &
