#!/bin/sh

# Include config file.
. ~/.config/lemonbar/.config

# Create switchable desktops.
bspc monitor -d One Two Three Four

# Per desktop sizing.
for desktop in $(bspc query -D); do
    bspc config -d $desktop border_width ${borderSize}
    bspc config -d $desktop window_gap ${gapSize}
done

# Universal sizing.
bspc config top_padding $((${gapSize} * 3))
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding $((${gapSize} * 3))
bspc config split_ratio 0.50

# Colors.
bspc config focused_border_color "${accent}"
bspc config normal_border_color "${background}"
bspc config presel_feedback_color "${accent}"

# Program specific rules.
bspc rule -a Steam state=floating follow=off

# Set a random wallpaper from a local collection.
localWallpapers=(~/.wallpaper/*)

if [[ ! -e /tmp/wallpaper.jpg ]]; then
    cp $(printf "%s\n" "${localWallpapers[RANDOM % ${#localWallpapers[@]}]}") /tmp/wallpaper.jpg
    feh --bg-fill /tmp/wallpaper.jpg
fi

# Set color-scheme-based wallpaper from the internet.
#wallpaperColor=$(echo ${accent} | tr -d "#")
#curl -o ~/.wallpaper/tiled/tweed.png "http://bg.siteorigin.com/image/generate/download?color=%23${wallpaperColor}&pattern=45degreee_fabric&blend=38&intensity=40.00&noise=0"
#feh --bg-tile ~/.wallpaper/tiled/tweed.png

# Start background programs.
compton --config ~/.config/compton/compton.conf -f &
dropbox &

# Start popup monitors.
~/.config/lemonbar/popups/updates &
~/.config/lemonbar/popups/battery &

# Start lemonbar panels.
~/.config/lemonbar/bars/status &
~/.config/lemonbar/bars/desktops &
