#!/bin/sh

# Include config file.
. ~/.config/lemonbar/.config

# Determine if a color has been specified by the popup command.
while getopts ":c:d:s:" opt; do
    case $opt in
        c) colorArg=${OPTARG} ;;
        d) durationArg=${OPTARG} ;;
        s) stringArg=${OPTARG} ;;
    esac
done

if [[ "${colorArg}" == "black" ]]; then
    popupBackground=$black; popupForeground=$foreground
elif [[ "${colorArg}" == "grey" ]]; then
    popupBackground=$grey; popupForeground=$background
elif [[ "${colorArg}" == "red" ]]; then
    popupBackground=$red; popupForeground=$background
elif [[ "${colorArg}" == "green" ]]; then
    popupBackground=$green; popupForeground=$background
elif [[ "${colorArg}" == "yellow" ]]; then
    popupBackground=$yellow; popupForeground=$background
elif [[ "${colorArg}" == "blue" ]]; then
    popupBackground=$blue; popupForeground=$background
elif [[ "${colorArg}" == "magenta" ]]; then
    popupBackground=$magenta; popupForeground=$background
elif [[ "${colorArg}" == "cyan" ]]; then
    popupBackground=$cyan; popupForeground=$background
elif [[ "${colorArg}" == "white" ]]; then
    popupBackground=$white; popupForeground=$background
else
    popupBackground=$background; popupForeground=$foreground
fi

if [[ ${durationArg} -le 0 ]]; then
    durationArg=3
fi

# Determine the duration of a popup based on length of the string.
# Calculations based on the assumption of the width of 5 spaces being equal to one word, and a reading rate of 200 words per minute.
stringWidth=$(($(txtw -s ${fontSize} "${stringArg}")))

# Determine the width of a popup based on the length of the string.
popupWidth=$((${stringWidth} * 2))

# Get static dimensions based on the bar panels.
popupHeight=${panelHeight}
popupX=${leftPanelX}
popupY=$((${panelHeight} * 2))

# Create a popup from whatever information is piped into this script.
(echo "%{c}${stringArg}"; sleep ${durationArg}) | lemonbar -g ${popupWidth}x${popupHeight}+${popupX}+${popupY} -f "${font}-${fontSize}" -f "${iconFont}" -B "${popupBackground}" -F "${popupForeground}" -d
